-- Tabel baru untuk fitur "Meta Testing" (Branding > Meta Testing).
-- Dijalankan manual terhadap database erp_sahada (Advertiser DB) — repo ini
-- belum punya sistem migrasi, jadi file ini disimpan sebagai catatan histori
-- skema saja, bukan runner otomatis.
CREATE TABLE IF NOT EXISTS meta_testing (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product_id INT NOT NULL,
  funnel VARCHAR(50) NOT NULL DEFAULT '',
  kategori VARCHAR(100) NOT NULL DEFAULT '',
  link_konten VARCHAR(500) NOT NULL DEFAULT '',
  nama_konten VARCHAR(255) NULL,
  tanggal_running DATE NULL,
  status_iklan VARCHAR(50) NOT NULL DEFAULT 'Menunggu ACC',
  spending DECIMAL(15,2) NOT NULL DEFAULT 0,
  total_lead INT NOT NULL DEFAULT 0,
  cpr DECIMAL(15,2) NOT NULL DEFAULT 0,
  hook_rate DECIMAL(5,2) NOT NULL DEFAULT 0,
  hold_rate DECIMAL(5,2) NOT NULL DEFAULT 0,
  ctr DECIMAL(5,2) NOT NULL DEFAULT 0,
  cpm DECIMAL(15,2) NOT NULL DEFAULT 0,
  closing INT NOT NULL DEFAULT 0,
  box INT NOT NULL DEFAULT 0,
  cr DECIMAL(5,2) NOT NULL DEFAULT 0,
  cpa DECIMAL(15,2) NOT NULL DEFAULT 0,
  cpa_persen DECIMAL(5,2) NOT NULL DEFAULT 0,
  layak_dianalisa VARCHAR(10) NOT NULL DEFAULT 'Belum',
  skor_cpr DECIMAL(6,2) NOT NULL DEFAULT 0,
  skor_cpm DECIMAL(6,2) NOT NULL DEFAULT 0,
  skor_ctr DECIMAL(6,2) NOT NULL DEFAULT 0,
  skor_hook DECIMAL(6,2) NOT NULL DEFAULT 0,
  skor_hold DECIMAL(6,2) NOT NULL DEFAULT 0,
  bonus_budget DECIMAL(6,2) NOT NULL DEFAULT 0,
  skor_konten DECIMAL(6,2) NOT NULL DEFAULT 0,
  skor_cr DECIMAL(6,2) NOT NULL DEFAULT 0,
  skor_cpa_persen DECIMAL(6,2) NOT NULL DEFAULT 0,
  bonus_volume DECIMAL(6,2) NOT NULL DEFAULT 0,
  skor_konvert DECIMAL(6,2) NOT NULL DEFAULT 0,
  skor_total DECIMAL(6,2) NOT NULL DEFAULT 0,
  peringkat INT NULL,
  grade VARCHAR(10) NULL,
  id_karyawan VARCHAR(50) NOT NULL DEFAULT '',
  nama_karyawan VARCHAR(150) NOT NULL DEFAULT '',
  diubah_oleh VARCHAR(150) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_meta_testing_product FOREIGN KEY (product_id) REFERENCES meta_ads_products(id) ON DELETE CASCADE,
  INDEX idx_meta_testing_product (product_id),
  INDEX idx_meta_testing_karyawan (id_karyawan)
);
